### ISSUE TITLE
Exeception when handling generic message on Picks tab in Grid mode

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#11]
As it says in the title of this issue, I have an error message with the Picks tab.
Here is the complet warrning:

15:36:20 - [LLCLIENTVIEW]: Exeception when handling generic message L'index étai
t hors limites. Il ne doit pas être négatif et doit être inférieur à la taille d
e la collection.
Nom du paramètre : index   à System.Collections.ArrayList.get_Item(Int32 index)
   à OpenSimProfile.Modules.OpenProfile.OpenProfileModule.HandlePickInfoRequest(
Object sender, String method, List`1 args)
   à OpenSim.Region.ClientStack.LindenUDP.LLClientView.HandleGenericMessage(ICli
entAPI sender, Packet pack) dans d:\opensim\mastergrid\OpenSim\Region\ClientStac
k\Linden\UDP\LLClientView.cs:ligne 6474

It happens in a single situation, a very specific situation.

Here's how to reproduce:
1) Go to the Picks tab and clear all and click OK to save and exit the profile
2) Go back to Picks tab and click on "New ..."
In this case you have the message warrning.
Sometimes it also occurs when you select the image.

After that, strangely, you can add, edit etc ... everything works fine.

So the problem is only present if you add your 1st Picks
It should without doubt add a little "if" somewhere ...

So, I hope this can help.

**Comment by kcozens** [comment]
I am unable to reproduce this problem. It may have been fixed as part of the changes made to address a couple of the points in issue #10.

**Comment by kcozens** [comment]
commit a56e71224618c1416893c0c652c6dcbfc54b1c64
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Tue Dec 5 12:30:10 2017 -0500

    Fixed issues with initial creation, and updating, of profile and profile picks
    Fixes issue #11 and #12.
