### ISSUE TITLE
show in search don't work

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#3]
The "show in shearch" checkbox isn't ckeckable
That with your dll and with osg dll, same problem.

**Comment by kcozens** [comment]
The main purpose of that checkbox is to control whether information about an avatar would appear in a website. A grid owner could allow a user to login to their account and change the setting. Changing the setting inworld isn't fully supported at this time. Closing as WONTFIX.

**Comment by djphil** [comment]
It is because it does not work that i pointed out, if it is not fixed one day, what is the interest of reporting it ?
