### ISSUE TITLE
All checkbox in notes tab don't work

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#4]
The "See when i am online" checkbox isn't ckeckable
The "Find me on the world map" checkbox isn't ckeckable
The "edit, delete or take my object" checkbox isn't ckeckable
That with your dll and with osg dll, same problem.

**Comment by kcozens** [comment]
I don't see any of those checkboxes appearing at the bottom of the Notes tab in Singularity. I have seen them when I looked at the notes tab in Firestorm. Those checkboxes duplicate the toggles available in the Friends list and I rarely use Firestorm. I'm closing this as WONTFIX. If someone else is motivated enough to provide a patch to make the checkboxes work in Firestorm this report can be reopened and the patch attached.

**Comment by djphil** [comment]
Disappointed to see that you were not motivated to make profile work properly and not only for Singularity users especially since Singularity is definitely not the best existing viewer ...

**Comment by kcozens** [comment]
I am motivated to make profile work, and it does. The extra buttons in the notes dialog box only appear in two of the 6 viewers I have on my machine. I found the checkboxes are active in at least three different grids. They can't be accessed if you are looking at your own profile.
