### ISSUE TITLE
Unable to connect to Profile Server  with mysqli

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#5]
When i use profile_mysqli.php i get this red warning.
If i use profile.php (mysql) i have no warning.

23:51:24 - [PROFILE]: Unable to connect to Profile Server http://myip.com/profile.php. Method avatar_properties_request, params Sy
stem.Collections.Hashtable. Exception System.Xml.XmlException: Il existe plusieu
rs éléments racine. Ligne 2, position 2.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.XmlTextReader.Read()
   à Nwc.XmlRpc.XmlRpcResponseDeserializer.Deserialize(TextReader xmlData)
   à Nwc.XmlRpc.XmlRpcRequest.Send(String url, Int32 timeout)
   à OpenSimProfile.Modules.OpenProfile.OpenProfileModule.GenericXMLRPCRequest(H
ashtable ReqParams, String method, String server)

**Comment by kcozens** [comment]
Someone else created the mysqli version of profile.php. I haven't tested it and the file will be deleted as soon when I commit the PHP file that uses PDO.

**Comment by djphil** [comment]
It's a shame, it was interesting to have mysqli which also works ...

**Comment by kcozens** [comment]
The mysqli version doesn't escape the parcel name in two SQL statements. I would be more inclined to keep the mysqli version if it had used parameter binding. I don't have the time to maintain both a mysqli version and a PDO version. The PDO version makes the mysqli obsolete unless someone is running a version of PHP that doesn't support PDO.

**Comment by kcozens** [comment]
commit 4519f0afd28740bc83d4892fbbfda1d971068a88
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Sun Apr 16 11:41:04 2017 -0400

    Updated profile_mysqli.php to keep it more in sync with the profile.php file.
    
    Use databaseinfo.php file. Escape parcelname in classified_update. Open
    (and close) database in one place. Use global $link to open database.
    
    One user really wanted a version using mysqli so this file was not deleted.
    This file is obsolete with the update of profile.php to use PDO so it may
    not be kept up-to-date or be as fully tested as the main profile.php file.
