### ISSUE TITLE
RegionLoaded patch

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#6]
Have you apply the patch proposed bu Ubit ?
Apparently no, here is:

on its source:
<pre>
        public void RegionLoaded(Scene scene)
        {
            // Hook up events
            scene.EventManager.OnNewClient += OnNewClient;
        }
</pre>
change to:
<pre>
        public void RegionLoaded(Scene scene)
        {
            if (!m_Enabled)
                return;

            // Hook up events
            scene.EventManager.OnNewClient += OnNewClient;
        }
</pre>
Source: http://opensimulator.org/mantis/view.php?id=8150#c31762

**Comment by kcozens** [comment]
Fixed in commit 99e61cb72b54325af93585df8e5ab8e93874a9fd
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Sun Apr 16 11:01:23 2017 -0400

    Added enabled check in RegionLoaded. Unhook event handler in RemoveRegion.
    Fixes issue #6.
