### ISSUE TITLE
Reference to OpenSimProfile missing in xxx.ini.example files

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#8]
In GridCommon.ini.example and Robust.HG.ini.example i see only:
ProfileURL = http://192.168.0.1/profile.php

I don't see:
Module = "OpenSimProfile";

Note : On OpenSim wiki the name for module is "OpenProfileModule" and on your repo, the name is "OpenSimProfile". This is a bit confusing ...

**Comment by kcozens** [comment]
There is no ProfileURL in either of those ini.example files in git master. Which wiki page references OpenProfileModule? Without seeing the page I would guess that the page is talking about the core profile module.

**Comment by djphil** [comment]
On STEP 3: OpenProfileModule here:
http://opensimulator.org/wiki/Profile

On STEP 3: OpenProfileModule here:
http://opensimulator.org/wiki/Profile_based_on_mysqli

**Comment by kcozens** [comment]
Both of those wiki pages is talking about the addon profile module. There is no ProfileURL in either of the two files you mentioned in a current copy of git master. A ProfileURL setting can be seen in OpenSimDefaults.ini but it is in the [UserProfiles] section and is part of the core profile module.

As to the module name mentioned in the wiki, the pages are out-of-date. The name mentioned is the old name for the module. The addon profile module comes with a README file which provides the information needed to use the OpenSimProfile module.

**Comment by djphil** [comment]
Yeah, i see you remove it ... (Commit e9b797)
[http://opensimulator.org/viewgit/?a=commit&p=opensim&h=e9b79719291567b92a9d5111b5939df20137469c](url)Commit e9b797
**Now** there is no longer, tank you!

I hope it will work soon ...

PS: What I wanted to say about the information on the wiki is that it is confusing because there are at least 3 places where information is found to install the profile and some information is obelious as you say.
