### ISSUE TITLE
Little report about Mysqli Profil

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimProfile#9]
1) 2nd Life Work 99%
I can add, remove, modify Photo and About
I can not check the "show in search", when i go back it remain unchecked (know bug)

2) Web work 100%
I can add, remove, modify the url and it persist

3) Interests work 100%
I can add, remove, modify all values

4) Picks work 100%
I can add, remove, modify all values and picture

5) Classfield work 50%
I can add but when i go back to see classified, picture is missing
I can delete

6) 1st Life work 100%
I can add, remove, modify Photo and Info (250 chars)

7) Notes work 0%
I get this warning
14:25:56 - [LLCLIENTVIEW]: Caught exception while processing OpenMetaverse.Packe
ts.AvatarNotesUpdatePacket for dj phil  System.MissingMethodException: Méthode i
ntrouvable : 'Boolean OpenSim.Region.Framework.Scenes.ScenePresence.get_isNPC()'
.
   à OpenSimProfile.Modules.OpenProfile.OpenProfileModule.AvatarNotesUpdate(ICli
entAPI remoteClient, UUID queryTargetID, String queryNotes)
   à OpenSim.Region.ClientStack.LindenUDP.LLClientView.HandleAvatarNotesUpdate(I
ClientAPI sender, Packet Pack) dans d:\opensim\standalone\OpenSim\Region\ClientS
tack\Linden\UDP\LLClientView.cs:ligne 12401
   à OpenSim.Region.ClientStack.LindenUDP.LLClientView.ProcessSpecificPacketAsyn
c(Object state) dans d:\opensim\standalone\OpenSim\Region\ClientStack\Linden\UDP
\LLClientView.cs:ligne 826

**Comment by djphil** [comment]
Tested with opensim-0.9.0-1246-gb52f7b9.zip 2017-04-15 09:56
http://opensimulator.org/viewgit/?a=commit&p=opensim&h=b52f7b920342b7ea3e0294eae054e7520801e339
Standaline without Hypergrid
Windows Seven 32Bits .NET Framework 4.6.2
Php 5.6.28

**Comment by djphil** [comment]
About 7) Notes work 0%
The problem seems to come from your dll
If I replace your dll by the osgrid dll then the notes work 100%

**Comment by djphil** [comment]
About 7) Notes work 0%
The problem is fixed with your commit 1fcb618dd2ee9d743b790e5ca81dd96b7478a951
Now Notes work 100%

**Comment by kcozens** [comment]
Please test setting/updating a picture for a classified ad. I do not see any problem with setting and updating pictures for a classified ad.

**Comment by kcozens** [comment]
I'm marking this as wontfix because I plan to remove the mysqli based PHP file in favour of the PDO based one.

**Comment by kcozens** [comment]
commit 229fe75d74e71486fe72ff75b9239d4bdbfa4c56
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Tue Dec 5 13:34:56 2017 -0500

    Untested fix for point 5 of issue #9, and possible bug when requesting notes.

**Comment by kcozens** [comment]
The PDO version of profile.php makes the mysqli based one obsolete so I will not be maintaining the mysqli based PHP file. I have pushed a couple of changes to the mysqli based PHP file. It may fix the issues reported but the changes are untested.
